# Multi-languages configure

zh-cn:
  title: Hugo NexT
  languageCode: zh-CN
  languageName: "简体中文"
  hasCJKLanguage: true
  languageDirection: ltr
  weight: 1
en-us:
  title: Hugo NexT
  languageCode: en-US
  languageName: English
  hasCJKLanguage: false
  weight: 2