name: Deploy Preliminary Site

on:
  push:
    branches:
      - develop

jobs:

  sync-2-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:hugo-next/hugo-next-docs.git
          destination-repo: git@gitee.com:hugo-next/hugo-next-docs.git

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0 

      - name: Setting variable
        env:
          ADD_THIS_ID: ${{ secrets.ADD_THIS_ID }}
          ALGOLIA_APIKEY: ${{ secrets.ALGOLIA_APIKEY }}
          ALGOLIA_APPID: ${{ secrets.ALGOLIA_APPID }}
          ALGOLIA_INDEXNAME: ${{ secrets.ALGOLIA_INDEXNAME }}
          ANALYTICS_LA_ID: ${{ secrets.ANALYTICS_LA_ID }}
          GISCUS_CATEGORY: ${{ secrets.GISCUS_CATEGORY }}
          GISCUS_CATEGORYID: ${{ secrets.GISCUS_CATEGORYID }}
          GISCUS_REPO: ${{ secrets.GISCUS_REPO }}
          GISCUS_REPOID: ${{ secrets.GISCUS_REPOID }}
          UTER_LABEL: ${{ secrets.UTER_LABEL }}
          UTER_REPO_NAME: ${{ secrets.UTER_REPO_NAME }}
          WALINE_SERVER_URL: ${{ secrets.WALINE_SERVER_URL }}
        run: sh .github/scripts/replace-vars.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true

      - name: Build Demo Sites
        run: |
              hugo --minify
              hugo -b /mist -e mist -d ./public/mist --minify
              hugo -b /muse -e muse -d ./public/muse --minify
              hugo -b /pisces -e pisces -d ./public/pisces --minify

      - name: Copy README & License
        run: |
              cp README.md README.zh.md ./public
              cp LICENSE ./public
              cp vercel.json ./public

      - name: Upload Algolia Indexes 
        uses: iChochy/Algolia-Upload-Records@main
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPID }}
          ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMINKEY }}
          INDEX_NAME: ${{ secrets.ALGOLIA_INDEXNAME }}
          FILE_PATH: "public/algolia.json"

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.RSA_PRIVATE_KEY }}
          external_repository: hugo-next/hugo-next.github.io
          publish_dir: "./public"        
          keep_files: false
          publish_branch: develop
          commit_message: ${{ github.event.head_commit.message }}

  push-site:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Push Site to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:hugo-next/hugo-next.github.io.git
          destination-repo: git@gitee.com:hugo-next/hugo-next.git